FROM node:20.13-alpine AS builder
WORKDIR /app
COPY pnpm-lock.yaml package.json ./
RUN npm i -g pnpm@9.0.6
RUN npm i -g vite@5.2.0
RUN pnpm i
COPY . .

ENV VITE_API_AUTH_SERVICE_URL=https://staging-user-auth.portaverse.co.id
ENV VITE_API_SOCIAL_SERVICE_URL=https://staging-social.portaverse.co.id
ENV VITE_API_NOTIFICATIONS_SERVICE_URL=https://staging-notification.portaverse.co.id
ENV VITE_API_COURSE_SERVICE_URL=https://staging-course.portaverse.co.id
ENV VITE_API_SEARCH_ENGINE_SERVICE_URL=https://staging-search-engine.portaverse.co.id
ENV VITE_SSO_URL=https://staging-sso.portaverse.co.id
ENV VITE_KMS_URL=https://staging-knowledge.portaverse.co.id
ENV VITE_LMS_URL=https://staging-learning.portaverse.co.id
ENV VITE_TMS_URL=https://staging-talent.portaverse.co.id
ENV VITE_MEET_URL=https://staging-meet.portaverse.co.id

RUN pnpm build

FROM nginx:stable-alpine AS server
COPY ./etc/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder ./app/dist /usr/share/nginx/html
EXPOSE 5001
CMD ["nginx", "-g", "daemon off;"]
